### ISSUE TITLE
Paging Error

### ISSUE THREAD

**Issue by julesx** [RolandPheasant/DynamicData#4]
This is thrown after I add an item to a bound collection. I can't really seem to narrow down the exact cause, and my stuff still all works.

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
   at DynamicData.Binding.SortedObservableCollectionAdaptor`2.<>c__DisplayClass5.<DoUpdate>b__6(Change`2 update) in C:\projects\dynamicdata\DynamicData\Binding\SortedObservableCollectionAdaptor.cs:line 90

   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
   at DynamicData.Binding.SortedObservableCollectionAdaptor`2.<>c__DisplayClass5.<DoUpdate>b__6(Change`2 update) in C:\projects\dynamicdata\DynamicData\Binding\SortedObservableCollectionAdaptor.cs:line 90
   at DynamicData.Kernel.EnumerableEx.ForEach[T](IEnumerable`1 source, Action`1 action) in C:\projects\dynamicdata\DynamicData\Kernel\EnumerableEx.cs:line 30
   at DynamicData.Binding.SortedObservableCollectionAdaptor`2.DoUpdate(ISortedChangeSet`2 updates, IObservableCollection`1 list) in C:\projects\dynamicdata\DynamicData\Binding\SortedObservableCollectionAdaptor.cs:line 82
   at DynamicData.Binding.SortedObservableCollectionAdaptor`2.Adapt(ISortedChangeSet`2 changes, IObservableCollection`1 collection) in C:\projects\dynamicdata\DynamicData\Binding\SortedObservableCollectionAdaptor.cs:line 59
   at DynamicData.DynamicDataEx.<>c__DisplayClass331`2.<Bind>b__333(ISortedChangeSet`2 updates) in C:\projects\dynamicdata\DynamicData\DynamicDataEx.cs:line 2505
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception)
   at System.Reactive.ExceptionHelpers.Throw(Exception exception)
   at System.Reactive.Stubs.<.cctor>b__1(Exception ex)
   at System.Reactive.AnonymousObserver`1.OnErrorCore(Exception error)
   at System.Reactive.ObserverBase`1.OnError(Exception error)
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception)
   at System.Reactive.ObserverBase`1.OnError(Exception error)
   at DynamicData.DynamicDataEx.<>c__DisplayClass331`2.<Bind>b__333(ISortedChangeSet`2 updates) in C:\projects\dynamicdata\DynamicData\DynamicDataEx.cs:line 2509

**Comment by RolandPheasant** [comment]
Try and implement a hash code on the object which includes the key field. It probably has something to do with hashing

**Comment by RolandPheasant** [comment]
If that does not work try adding the key field as an extra field on the sortexpressioncomparer.

**Comment by RolandPheasant** [comment]
and if that fails, can you copy the entire ItemVm object  + the SortComparer  and I will try and replicate it

**Comment by julesx** [comment]
I made GetHashCode return my unique itemVm Id, no change.

i don't see where to add a key field

my sort comparer is really simple
                SortController.Change(SortExpressionComparer<TItemVm>.Descending(t => t.Name));

my itemvm is pretty big but not really complicated...

i investigated a bit more and this is the trigger
```
                DynamicDataVm.ItemCache.Clear();
                DynamicDataVm.ItemCache.AddOrUpdate(MyList<ItemVm>);
                DynamicDataVm.Connect()....
.Subscribe();
```

i said earlier this occurs when i change the collection, that was incorrect. it seems to happen when i call this pattern repeatedly even when the list doesnt change. perhaps my usage could be improved

**Comment by RolandPheasant** [comment]
You should only ever call connect once to initialise the stream. Have a look at the dynamic.trader example. Perhaps that is it

**Comment by RolandPheasant** [comment]
Also sortexpressioncomparer.ascending(t=>t.name).thenascending...

**Comment by julesx** [comment]
Is there an easy way to check if an ItemCache is connected to an OC already?

**Comment by RolandPheasant** [comment]
in constructor of vm do:

var connected = ItemCache.Connect().......Page().Bind().Subscribe() 

There is no need to ever resubscribe as reactive ex / dynamic data takes care of the rest.

And treat calling ItemCache,AddOrUpdate(..) / ItemCache.Clear(..) etc as a completely different operation which can be called multiple times. Then the bindings will look after themselves

**Comment by julesx** [comment]
niiiiice
